version: "3.9"

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"           # если захочешь дергать ollama снаружи
    volumes:
      - ollama:/root/.ollama    # чтобы модели не исчезали при пересборке

  backend:
    build: ./backend
    container_name: dh_backend
    restart: unless-stopped
    environment:
      DATABASE_URL: "sqlite:///./data/app.db"

      # настройки для backend/app/ollama_client.py
      OLLAMA_BASE_URL: "http://ollama:11434"
      OLLAMA_MODEL: "llama3.2:1b"
      OLLAMA_TIMEOUT: "900.0"

    volumes:
      - ./backend/app:/app/app
      - ./backend/data:/app/data
    ports:
      - "8000:8000"
    depends_on:
      - ollama

volumes:
  ollama:
